# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa323bc07c30c789bd5f872f0583dff23204bb4fb9c9b78b5730e9fcb5d52148c6bcbc80c4c5acf29eca863d7509814a2c302ab74ef0c615564d263ea47d7ef7

test:
  secret_key_base: 9c1e4313257ed3008abc50c138c8a5f5d87069f37c395f86c2d3b7ad00355943dbaeeb51c6eb64342a0242df5803ef13e784a38cbfdefb40ab1e4abe798c701e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
